# Project information
site_name: Beeping Documentation
site_description: The landing page for Beeping documentation.
site_author: Beeping LLC
site_url: https://beeping.io

# Page tree
nav:
    - Index: index.md
    - About: about.md    

# Theme configuration
theme:
  name: 'material'  
  custom_dir: 'theme'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/brand.png'
  feature:
    tabs: true
  font:
    text: 'Graphik-Regular'
    code: 'Graphik-Light'
  palette:
    primary: 'red'
    accent: 'light blue'

extra_css:
  - 'assets/stylesheets/beeping.css'
  - 'assets/fonts/beeping/graphik/graphik.css'

# Repository
repo_name: beeping-docs
repo_url: https://github.com/beeping-io/beeping-docs
edit_uri: ""

# Copyright
copyright: 'Apache License, Version 2.0'
