# Project information
site_name: Beeping Documentation
site_description: The landing page for Beeping documentation.
site_author: Beeping LLC
site_url: https://beeping.io

# Page tree
nav:
    - Welcome: index.md       

# Theme configuration
theme:
  name: 'material'  
  custom_dir: 'theme'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/brand.png'
  feature:
    tabs: true
  font: false    
  palette:
    primary: 'red'
    accent: 'light blue'

# Customization    
extra_css:
  - 'assets/stylesheets/beeping.css'
  - 'assets/fonts/beeping/graphik/graphik.css'

# Customization
extra:
  social:    
    - type: github-alt
      link: https://github.com/beeping-io    

# Repository
repo_name: beeping-docs
repo_url: https://github.com/beeping-io/beeping-docs
edit_uri: ""

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Copyright
copyright: 'Apache License, Version 2.0'
