# Project information
site_name: Beeping Documentation
site_description: The landing page for Beeping documentation.
site_author: Beeping LLC
site_url: https://beeping.io

nav:
  - Home: index.md
  - About: about.md
